language: php

matrix:
  include:
    - php: 5.6
    - php: 7

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit --exclude-group=none

branches:
  only:
    - master
    - develop
