language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - make dependencies

script:
  - make test
  - git log $(git describe --abbrev=0 --tags)...HEAD --no-merges --pretty=format:"* [%h](http://github.com/${TRAVIS_REPO_SLUG}/commit/%H) %s (%cN)"

branches:
  only:
    - master
    - develop
